### PR TITLE
Decline version bump for ip upgrade

### PR DESCRIPTION
**Pull request by tilgovi**

### CODE REVIEW

**Comment by tilgovi** [comment]
I'm seeing checks fail and I think it's maybe just because I merged the dependabot PR and that didn't include a version bump?

**Comment by smoores-dev** [comment]
I don't think that would be the case. Once it's merged into main, I don't think yarn cares whether there's a version bump for it

**Comment by tilgovi** [comment]
I'll rebase that branch on here and we'll see!

**Comment by tilgovi** [comment]
😆 Doesn't like having multiple versioning files in the branch. I will... try again?

**Comment by tilgovi** [comment]
Ah. I must have based it on a branch that no longer existed or something. All sorted.

**Pull request closed without merging**
