### PR TITLE
0.4.1

### PR DESCRIPTION
**Pull request by saranrapjs**

### CODE REVIEW

**Comment by smoores-dev** [comment]
Oh hey, there's a goof here when you run `yarn version apply`, where it creates or leaves an empty shell of a version file that messes stuff up later. You can either run `yarn version apply --all` (which is supposed to be for monorepos, but actually works) instead, or just manually delete that empty version file here

**Comment by smoores-dev** [comment]
https://github.com/yarnpkg/berry/issues/5316 -- for reference

**Comment by saranrapjs** [comment]
Corrected here — and also cleaned up some files that I guess I'd orphaned from my last version bump. Thank you for riding along on my yarn berry versioning journey.

**Review by smoores-dev — APPROVED** [review]

**Comment by smoores-dev** [comment]
@saranrapjs did you figure out publishing permissions, or would you like me to publish this one as well?

**Comment by saranrapjs** [comment]
i read the instructions but have not yet summoned people to add me to the npm account — so if you're able to publish this one as well, i solemnly swear the next time i will be prepared to DIY!

**Comment by smoores-dev** [comment]
Hahaha no worries at all. Will do!

**Pull request merged**
